/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RentalMotor;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 3
 */
public class Rental extends javax.swing.JFrame {

    /**
     * Creates new form Rental
     */
    public Rental() {
        setIcon(); // icon
        initComponents();
        // setting ke tengah center
        Dimension window = Toolkit.getDefaultToolkit().getScreenSize();
        int x = window.width / 2 - this.getSize().width / 2;
        int y = window.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        // TANGGAL
        tampiltanggal();
        
        //disble jenis kendaraan,total dan kembalian
        jeniskendaraan.disable();
        totalbayar.disable();
        kembalian.disable();
        hargasewa.disable();
        biayamotor.disable();
    }
    //method date today
    public void tampiltanggal(){
        Date tgl = new Date();
        SimpleDateFormat aa = new SimpleDateFormat("dd-MM-yyyy");
        Tanggal.setText(aa.format(tgl));
    }
    
    //method jumlah karakter
    public void JumlahKarakter(KeyEvent a) {
        if (transaksi.getText().length()==4){
            a.consume();
            JOptionPane.showMessageDialog(null,
                    "Maximum 4 Characters",
                    "Warning!",JOptionPane.WARNING_MESSAGE);
        }
    }
    
        //method jumlah karakter sewa
    public void JumlahKarakterSewa(KeyEvent c) {
        if (lamasewa.getText().length()==2){
            c.consume();
            JOptionPane.showMessageDialog(null,
                    "Maximum 2 Characters",
                    "Warning!",JOptionPane.WARNING_MESSAGE);
        }
    }
     //method hanya angka
    public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,
                    "Enter Only Numbers",
                    "Warning!",JOptionPane.WARNING_MESSAGE
            );
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Plat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jeniskendaraan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hargasewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lamasewa = new javax.swing.JTextField();
        pilihmotor = new javax.swing.JLabel();
        Motor = new javax.swing.JComboBox<>();
        biaya = new javax.swing.JLabel();
        biayamotor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalbayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        uangbayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI RENTAL MOTOR (KELOMPOK 3)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KELOMPOK 3 UAS OOP - APLIKASI RENTAL MOTOR ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("No.Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 20));

        transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transaksiKeyTyped(evt);
            }
        });
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 60, -1));
        getContentPane().add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Plat Nomor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 84, 80, -1));

        Plat.setForeground(new java.awt.Color(255, 255, 255));
        Plat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AG789KBX", "AG689KDC", "AG852BDA", "AG329LOX", "AG229OGX", "AG889YTX" }));
        Plat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatActionPerformed(evt);
            }
        });
        Plat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PlatKeyTyped(evt);
            }
        });
        getContentPane().add(Plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 106, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Jenis Kendaraan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, 20));

        jeniskendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeniskendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(jeniskendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 106, 82, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Harga Sewa /Hari");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 84, -1, -1));

        hargasewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargasewaActionPerformed(evt);
            }
        });
        getContentPane().add(hargasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 106, 92, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Lama Sewa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 84, -1, -1));

        lamasewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamasewaKeyTyped(evt);
            }
        });
        getContentPane().add(lamasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 106, 91, -1));

        pilihmotor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        pilihmotor.setForeground(new java.awt.Color(255, 255, 51));
        pilihmotor.setText("Pilih Motor");
        getContentPane().add(pilihmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 149, 80, -1));

        Motor.setForeground(new java.awt.Color(255, 255, 255));
        Motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Yamaha", "Suzuki", "Kawasaki", "Benelli" }));
        Motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorActionPerformed(evt);
            }
        });
        getContentPane().add(Motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 146, 117, -1));

        biaya.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        biaya.setForeground(new java.awt.Color(255, 255, 0));
        biaya.setText("Biaya Motor");
        getContentPane().add(biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 183, -1, -1));

        biayamotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayamotorActionPerformed(evt);
            }
        });
        getContentPane().add(biayamotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 180, 117, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Total Bayar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, -1));

        totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbayarActionPerformed(evt);
            }
        });
        getContentPane().add(totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 208, 125, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Uang Bayar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        uangbayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                uangbayarFocusLost(evt);
            }
        });
        uangbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangbayarActionPerformed(evt);
            }
        });
        uangbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uangbayarKeyTyped(evt);
            }
        });
        getContentPane().add(uangbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 248, 125, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 0));
        jLabel10.setText("Kembalian");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 288, 125, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("COUNT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 340, 80, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 340, -1, -1));

        Bg.setForeground(new java.awt.Color(0, 0, 0));
        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RentalMotor/123.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jeniskendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeniskendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeniskendaraanActionPerformed

    private void hargasewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargasewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargasewaActionPerformed

    private void biayamotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayamotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayamotorActionPerformed

    private void totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalbayarActionPerformed

    private void uangbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangbayarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    // setting function keluar 
        if (JOptionPane.showConfirmDialog(null,
                "Are you sure out?",
                "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //setting function menu baru 
        transaksi.setText("");
        jeniskendaraan.setText("");
        hargasewa.setText("");
        lamasewa.setText("");
        biayamotor.setText("");
        totalbayar.setText("");
        uangbayar.setText("");
        kembalian.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void transaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transaksiKeyTyped
        // TODO add your handling code here:
        
        //PANGGIL JUMLAH KARAKTER
        JumlahKarakter(evt);
        FilterAngka(evt); 
    }//GEN-LAST:event_transaksiKeyTyped

    private void PlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatActionPerformed
        // TODO add your handling code here:
        // SET NOMOR PLAT dan jenis nya dan harga sewa
        if(Plat.getSelectedItem()=="AG789KBX"){
            jeniskendaraan.setText("Motor Matic");
            hargasewa.setText("200000");
        } 
        else if (Plat.getSelectedItem()=="AG689KDC"){
            jeniskendaraan.setText("Motor Bebek");
            hargasewa.setText("300000");
        }
        else if (Plat.getSelectedItem()=="AG852BDA"){
            jeniskendaraan.setText("Motor Sport");
            hargasewa.setText("400000");
        }
        else if (Plat.getSelectedItem()=="AG329LOX"){
            jeniskendaraan.setText("Motor Matic");
            hargasewa.setText("200000");
        }
        else if (Plat.getSelectedItem()=="AG229OGX"){
            jeniskendaraan.setText("Motor Sport");
            hargasewa.setText("400000");
        }
        
        else {
            jeniskendaraan.setText("Motor Pribadi");
            hargasewa.setText("500000");
                }
    }//GEN-LAST:event_PlatActionPerformed

    private void PlatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PlatKeyTyped

    private void MotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorActionPerformed
        // TODO add your handling code here:
        
        //set harga jenis motor
       if(Motor.getSelectedItem()=="Honda"){
           biayamotor.setText("25000");
       }
       else if(Motor.getSelectedItem()=="Yamaha"){
           biayamotor.setText("50000");
       }
       else if(Motor.getSelectedItem()=="Suzuki"){
           biayamotor.setText("50000");
       }
       else if(Motor.getSelectedItem()=="Kawasaki"){
           biayamotor.setText("25000");
       }
       else {
           biayamotor.setText("0");
       }
    }//GEN-LAST:event_MotorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //total bayar
        int sewa = Integer.parseInt(hargasewa.getText());
        int lama = Integer.parseInt(lamasewa.getText());
        int bimot = Integer.parseInt(biayamotor.getText());
        int ttlbyr;
        
        ttlbyr = ((sewa * lama)+bimot);
        totalbayar.setText(Integer.valueOf(ttlbyr).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uangbayarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uangbayarFocusLost
        // TODO add your handling code here:
        
        // RUMUS uang bayar dan kembalian
        
        int cektotal = Integer.parseInt(totalbayar.getText());
        int cekbayar = Integer.parseInt(uangbayar.getText());
     
        if(cekbayar < cektotal){
            JOptionPane.showMessageDialog(null,
                    "Money Paid is Less Than the Total Paid",
                    "Warning!",JOptionPane.WARNING_MESSAGE);
        } 
        else {
            int hitungkembali;
            hitungkembali = cekbayar - cektotal;
            kembalian.setText(Integer.valueOf(hitungkembali).toString());
        }
    }//GEN-LAST:event_uangbayarFocusLost

    private void lamasewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamasewaKeyTyped
        // TODO add your handling code here:
        
        //filter angka
        FilterAngka(evt); 
        JumlahKarakterSewa(evt);
    }//GEN-LAST:event_lamasewaKeyTyped

    private void uangbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangbayarKeyTyped
        // TODO add your handling code here:
        //filter angka
        FilterAngka(evt); 
    }//GEN-LAST:event_uangbayarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JComboBox<String> Motor;
    private javax.swing.JComboBox<String> Plat;
    private javax.swing.JTextField Tanggal;
    private javax.swing.JLabel biaya;
    private javax.swing.JTextField biayamotor;
    private javax.swing.JTextField hargasewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jeniskendaraan;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField lamasewa;
    private javax.swing.JLabel pilihmotor;
    private javax.swing.JTextField totalbayar;
    private javax.swing.JTextField transaksi;
    private javax.swing.JTextField uangbayar;
    // End of variables declaration//GEN-END:variables
    
    //function create icon pojok
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
    }
}
